[project]
name = "matrx-dream-service"
version = "0.0.1"
description = "Matrx service"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.1.0",
    "githubkit>=0.12.16",
    "matrx-utils @ git+https://github.com/armanisadeghi/matrx-utils.git@v1.0.0",
]

[project.scripts]
matrx = "matrx_dream_service.cli:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.hatch.build.targets.wheel]
packages = ["src/matrx_dream_service"]


[tool.setuptools]
include-package-data = true
